- hosts: all
  name: Apply a configuration from a file 
  gather_facts: false
  become: true
  vars:
  tasks:
    - name: Do some configuring
      eos_config:
        src: cfg/{{ inventory_hostname }}.cfg